import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Touch Typing',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const modifiedClass = `bg-dolphin-bg ${inter.className}`
  return (
    <html lang="en">
      <body className={modifiedClass}>{children}</body>
    </html>
  )
}
